In [1]:
import numpy as np

In [47]:
# create random np array of ints --> max value 
randomIntMatrix = np.random.randint(5,size=(8,8))
randomIntMatrix

array([[1, 0, 0, 3, 3, 3, 2, 3],
       [2, 4, 2, 3, 2, 1, 2, 4],
       [2, 0, 1, 4, 4, 0, 0, 1],
       [2, 3, 2, 3, 2, 1, 3, 3],
       [4, 2, 3, 1, 0, 2, 2, 4],
       [3, 1, 1, 0, 2, 0, 4, 4],
       [2, 3, 0, 2, 0, 4, 1, 1],
       [1, 2, 4, 3, 0, 1, 1, 4]])

In [48]:
# create np array of ones
onesMatrix = np.ones((4,4))
onesMatrix

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [49]:
zerosMatrix = np.zeros((3,3))
zerosMatrix

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [50]:
# get the first three columns of the randomInt
randomIntMatrix[:,0:3]

array([[1, 0, 0],
       [2, 4, 2],
       [2, 0, 1],
       [2, 3, 2],
       [4, 2, 3],
       [3, 1, 1],
       [2, 3, 0],
       [1, 2, 4]])

In [55]:
# create two 1D arrays and stack them horizontaly

array1 = np.random.randint(100,size=(20))
array1

array2 = np.random.randint(100,size=(20))
array2



array([66, 80, 72, 22, 21, 90,  7, 53, 39, 88, 66, 28, 84, 21, 62, 44,  7,
       95, 61, 74])

In [57]:
np.vstack((array1,array2))

array([[75, 95, 69, 77, 91,  7, 76,  3, 82, 39, 23, 84,  7, 85, 47, 85,
         1, 63, 76, 37],
       [66, 80, 72, 22, 21, 90,  7, 53, 39, 88, 66, 28, 84, 21, 62, 44,
         7, 95, 61, 74]])

In [62]:
array1.reshape(-1,5)

array([[75, 95, 69, 77, 91],
       [ 7, 76,  3, 82, 39],
       [23, 84,  7, 85, 47],
       [85,  1, 63, 76, 37]])

In [63]:
array1

array([75, 95, 69, 77, 91,  7, 76,  3, 82, 39, 23, 84,  7, 85, 47, 85,  1,
       63, 76, 37])

In [72]:
a = np.reshape(array1,(-1,1))

In [73]:
b = np.reshape(array2,(-1,1))

In [79]:
c = np.hstack((a,b))

In [82]:
np.reshape(c,(2,-1))

array([[75, 66, 95, 80, 69, 72, 77, 22, 91, 21,  7, 90, 76,  7,  3, 53,
        82, 39, 39, 88],
       [23, 66, 84, 28,  7, 84, 85, 21, 47, 62, 85, 44,  1,  7, 63, 95,
        76, 61, 37, 74]])